### PR TITLE
add go.mod, update to github.com/oakmound/oak/v2 and fix build

### PR DESCRIPTION
**Pull request by mewmew**

### CODE REVIEW

**Comment by mewmew** [comment]
Not sure what the contribution guidelines are for oakmound projects. In either case, I hereby release this code change into the public domain. (obviously silly, since I didn't even write the code. `go mod tidy` did).

Cheers,
Robin

**Comment by 200sc** [comment]
LGTM, thanks!

We don't have contribution guidelines for these side forks yet-- license wise I'll update this to match oak (Apache 2.0), however, given its seeing use.

**Comment by 200sc** [comment]
Correction-- we're under MIT as required by the project we forked from

**Comment by justinclift** [comment]
@200sc When you say "side fork", what are you meaning?  Is there another Go "ofbx" repo this came from?

**Comment by 200sc** [comment]
No, we're just respecting the license of the C project this is a conversion of: https://github.com/nem0/OpenFBX

**Comment by justinclift** [comment]
No worries, thanks. :smile:

**Pull request merged**
